### ISSUE TITLE
Special characters in include statements are not handled correctly

### ISSUE THREAD

**Issue by edgar79** [openlilylib/LO-ly#27] opened 2019-05-27 12:48 UTC
Hello,

I tested the include statements on Linux, macOS, and Windows again
and found that there is a bug when special characters like german ä are in the path using Windows.

The function `WindowsCommand` writes a batch file, and i assume the file encoding is UTF-8 but cmd.exe seems to expect codepage 850.

I am searching for a workaround…

Cheers,
Hannes E. Schäuble

**Comment by uliska** [comment] 2019-05-27 14:55
Are you sure that the problem is not on the side of LilyPond itself? IIRC LilyPond (or rather GhostScript) doesn't like Umlauts in filenames at all.

**Comment by KlausBlum** [comment] 2019-05-27 16:57
Hello back, 

I've found and tested a workaround: 
https://www.libe.net/Robocopy-Umlaute
Hannes is right: By default, *.bat and *.cmd files expect OEM 850 encoding. 
But according to the above website, it is possible to select another character set by adding `chcp 1252` at the beginning of the batch file. I've tested that and it worked for me (Windows 10). 
I will modify the windows command to include that.

**Comment by KlausBlum** [comment] 2019-05-27 18:32
Merged. 
Hannes, thanks for reporting that. I didn't know that there was a problem. 
Still anything missing before we can close the issue?

**Comment by edgar79** [comment] 2019-05-27 18:46
I was just searching for a general solution (cp 1252 covers only Western European languages).
I found `TextInputStream` has the function `setEncoding()`. I don't yet know if `TextOutputStream` has getEncoding or setEncoding - but if it has, we could use `BatchFileOutputStream.getEncoding()` to get the currently used encoding and set this inside the batch file using `chcp`. A solution like this would cover more languages.

**Comment by edgar79** [comment] 2019-05-28 11:23
I found no reliable way to get the currently used codepage (using LibreOffice Basic)
but in the pull request #28 I used `TextOutputStream.setEncoding("utf-8")` and then `chcp 65001` which should be the corresponding codepage. Additionally I inserted a few `Chr(13)` to get it working again.

**Comment by edgar79** [comment] 2019-05-28 11:35
Hello @KlausBlum ,
If you test the pull request and if you merge it - could you publish a fixed release?

**Comment by KlausBlum** [comment] 2019-05-28 17:14
Hi Hannes, 
thanks for your work. Really sounds more reliable than what I've found. 
To be honest, there's pretty much code from Samuel (the original OLy developer) that I don't entirely understand...  ;-)
Maybe it will take until tomorrow that I find the time, but I will publish a 0.5.10 release. 

Cheers, 
Klaus

**Comment by KlausBlum** [comment] 2019-05-28 17:18
Hallo Hannes, 
es ist eigentlich unpraktisch, dass man auf GitHub keine privaten Nachrichten schreiben kann, oder zumindest E-Mail-Adressen austauschen... 
Ich bin erreichbar unter benbignoise@gmx.de 
(Diesen Kommentar lösche ich in ein paar Minuten wieder, aber bis dahin ist die Mail ja schon unterwegs.)

Viele Grüße, 
Klaus Blum

**Comment by edgar79** [comment] 2019-05-29 16:59
Hi Klaus,
like written in my mail I thank you for all your positive feedback.
I think we can close this issue now.

Cheers,
Hannes

**Comment by KlausBlum** [comment] 2019-05-29 21:57
Hi Hannes, 
thanks for all your help. Welcome to 0.5.10  ;-)
Now let's hit that "Close" button...

**Closed by KlausBlum** 2019-05-29 21:57 UTC
